import type { Metadata } from "next";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Vamos dar um beijo ?",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-Br">
      <body>
        {children}
      </body>
    </html>
  );
}
